In [1]:
# Exp.no:3
# Aim:To perform basics of data frame.
# Name:Vedanti B. Tayade
# Roll no:65
# Sec:B
# Sub:ET1
# Date:07/08/2025

# Creating Series

In [2]:
import pandas as pd

In [3]:
Name=["Vedanti","Shrutika","Sakshi","Pranali","Himani","Sanika","Shrushti","Indrani"]
Name

['Vedanti',
 'Shrutika',
 'Sakshi',
 'Pranali',
 'Himani',
 'Sanika',
 'Shrushti',
 'Indrani']

In [4]:
print(Name)

['Vedanti', 'Shrutika', 'Sakshi', 'Pranali', 'Himani', 'Sanika', 'Shrushti', 'Indrani']

In [5]:
Roll_list=pd.Series(Name,index=[1,2,3,4,5,6,7,8])
print(Roll_list)

1     Vedanti
2    Shrutika
3      Sakshi
4     Pranali
5      Himani
6      Sanika
7    Shrushti
8     Indrani
dtype: object

 # Creating Data Frame

In [6]:
import pandas as pd

In [7]:
df=pd.DataFrame([[1,2,3,4],[7,8,9,5],[6,8,4,6],[8,5,6,9]],
columns=["CD","DSS","CAO","DBMS"])

In [8]:
df

   CD  DSS  CAO  DBMS
0   1    2    3     4
1   7    8    9     5
2   6    8    4     6
3   8    5    6     9

In [9]:
df.shape

(4, 4)

In [10]:
df.size

16

In [11]:
df.ndim

2

# Adding Record (Row) to the data frame

In [12]:
df2=pd.DataFrame([[10,20,30,40]],
columns=["CD","DSS","CAO","DBMS"])

In [13]:
df3=df.append(df2,ignore_index=True)

In [14]:
df3

   CD  DSS  CAO  DBMS
0   1    2    3     4
1   7    8    9     5
2   6    8    4     6
3   8    5    6     9
4  10   20   30    40

In [15]:
df3.shape

(5, 4)

In [16]:
df3.size

20

In [17]:
df3.ndim

2

# Adding attribute (columns) name DM

In [18]:
df3["DM"]=[3,6,5,8,7]

In [19]:
df3

   CD  DSS  CAO  DBMS  DM
0   1    2    3     4   3
1   7    8    9     5   6
2   6    8    4     6   5
3   8    5    6     9   8
4  10   20   30    40   7

# Deleting Record from df3 data frame

In [20]:
df4=df3.drop(index=[1])

In [21]:
df4

   CD  DSS  CAO  DBMS  DM
0   1    2    3     4   3
2   6    8    4     6   5
3   8    5    6     9   8
4  10   20   30    40   7

# Deleting Attribute (columns)from df3 dataframe

In [22]:
df5=df3.drop(columns=['DM'])

df5

# Finding Mean Median Mode

In [23]:
print("mean of DSS:",df5["DSS"].mean())

mean of DSS: 8.6

In [24]:
print("median of DSS:",df5["DSS"].median())

median of DSS: 8.0

In [25]:
print("mode of DSS:",df5["DSS"].mode())

mode of DSS: 0    8
dtype: int64